### ISSUE TITLE
result item write without square bracket when the item stored in array

### ISSUE THREAD

**Issue by ramakc153** [ramakc153/payandtax#1]
how to write item result if the item more than one without the square brackets ? i stored the item data in an array

![image](https://user-images.githubusercontent.com/72650027/174938478-ea193ea1-34e2-4991-8538-71584c986597.png)

 for example "Anda membeli kaset, Basara, Downhill dengan harga Rp. 683.342

**Comment by pelgabalawy** [comment]
Hi, I can take that issue.
Is this the format you want your results to be in?
![image](https://user-images.githubusercontent.com/38790601/174942633-7516da12-708c-475c-84d8-8cfe25b8bf61.png)

**Comment by Ni3dzwi3dz** [comment]
I volunteer as well :D

**Comment by ramakc153** [comment]
> Hi, I can take that issue. Is this the format you want your results to be in? ![image](https://user-images.githubusercontent.com/38790601/174942633-7516da12-708c-475c-84d8-8cfe25b8bf61.png)



> Hi, I can take that issue. Is this the format you want your results to be in? ![image](https://user-images.githubusercontent.com/38790601/174942633-7516da12-708c-475c-84d8-8cfe25b8bf61.png)

yeah that's the result that i expected. do you mind to share the code ?

**Comment by ramakc153** [comment]
> Hi, I can take that issue. Is this the format you want your results to be in? ![image](https://user-images.githubusercontent.com/38790601/174942633-7516da12-708c-475c-84d8-8cfe25b8bf61.png)

yes that's the result that i expected. do you mind to share the code ?

**Comment by pelgabalawy** [comment]
sure!, The thing is that I thought you needed contribution to your repo, but I guess you just want your question answered
![image](https://user-images.githubusercontent.com/38790601/175199727-09e3af7f-c8bb-41ca-a540-fec242ed671b.png)

**Comment by ramakc153** [comment]
thanks for sharing the code bro.

yea i'm still new to github, still learning to get use of it. thanks for the suggestion.

**Comment by ramakc153** [comment]
> I volunteer as well :D

thanks for help!
